modLoader = "kotlinforforge"
loaderVersion = "[${versions.kotlin_forge},)"
license = "MIT"

[[mods]]
modId = "hexcellular"
version = "${modVersion}"
displayName = "Hexcellular"
logoFile = "icon.png"
authors = "miyucomics"
description = "Adds property iota for simple iota storage, state keeping, and syncing."

[[dependencies.hexcellular]]
modId = "minecraft"
mandatory = true
versionRange = "[${versions.minecraft},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexcellular]]
modId = "forge"
mandatory = true
versionRange = "[${versions.forge_dependency},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexcellular]]
modId = "hexcasting"
mandatory = true
versionRange = "[${versions.hexcasting_dependency},)"
ordering = "NONE"
side = "BOTH"